name: titan
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - pytorch
dependencies:
  - python=3.9
  - ipykernel
  - pyvips
  - libvips
  - pip
  - pytorch=2.8.*        # CUDA 12 build
  - torchvision=0.15.*   # CUDA 12 build
  - torchaudio=2.8.*     # CUDA 12 build
  - pip:
      - albumentations==2.0.8
      - cmake==4.0.3
      - cucim==23.10.0
      - cupy-cuda12x==13.6.0
      - einops-exts==0.0.4
      - en-core-sci-lg==0.5.4
      - h5py==3.14.0
      - ipywidgets==8.1.7
      - lit==18.1.8
      - opencv-python==4.9.0.80
      - pkgconfig==1.5.5
      - python-dotenv==1.1.1
      - pyvips==3.0.0
      - scispacy==0.5.5
      - seaborn==0.13.2
      - timm==1.0.3
      - transformers==4.56.1
      - umap-learn==0.5.9.post2
